<?php

/**
 * @file
 * Contains custommail.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custommail_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
            // Main module help for the custommail module.
        case 'help.page.custommail':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Testing Email sending') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function custommail_theme() {
    return [
        'custommail' => [
            'render element' => 'children',
        ],
    ];
}

function customMailSend($to, $params)
{
    $mailManager = \Drupal::service('plugin.manager.mail');
    $params['headers'] = 'text/html';
    return $mailManager->mail('custommail', 'sending_email_to_user', $to, null, $params, true);
}

//custommail
//sending_email_to_user
/**
* Implements hook_mail().
*/

function custommail_mail($key, &$message, $params) {
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = $params['subject'];
    //            $message['body'][] = $params['message'];
    $message['body'] = $params['body'];

}
